/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/activity-api';
export * from './api/customer-api';
export * from './api/default-api';
export * from './api/project-api';
export * from './api/tag-api';
export * from './api/team-api';
export * from './api/timesheet-api';
export * from './api/user-api';

