/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiActivitiesIdMetaPatchRequest
 */
export interface ApiActivitiesIdMetaPatchRequest {
    /**
     * The meta-field name
     * @type {string}
     * @memberof ApiActivitiesIdMetaPatchRequest
     */
    'name': string;
    /**
     * The meta-field value
     * @type {string}
     * @memberof ApiActivitiesIdMetaPatchRequest
     */
    'value': string;
}

