/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiTimesheetsIdRestartPatchRequest
 */
export interface ApiTimesheetsIdRestartPatchRequest {
    /**
     * Whether data should be copied to the new entry. Allowed values: all, tags (deprecated), rates (deprecated), description (deprecated), meta (deprecated) (default: nothing is copied)
     * @type {string}
     * @memberof ApiTimesheetsIdRestartPatchRequest
     */
    'copy'?: string;
    /**
     * Changes the restart date to the given one (default: now)
     * @type {string}
     * @memberof ApiTimesheetsIdRestartPatchRequest
     */
    'begin'?: string;
}

