/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerMeta } from './customer-meta';
// May contain unused imports in some cases
// @ts-ignore
import { Team } from './team';

/**
 * 
 * @export
 * @interface CustomerEntity
 */
export interface CustomerEntity {
    /**
     * 
     * @type {number}
     * @memberof CustomerEntity
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'comment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerEntity
     */
    'visible': boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'company'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'vatId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'contact'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'currency': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'fax'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'mobile'?: string;
    /**
     * Limited via RFC to 254 chars
     * @type {string}
     * @memberof CustomerEntity
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'homepage'?: string;
    /**
     * Length was determined by a MySQL column via \"use mysql;describe time_zone_name;\"
     * @type {string}
     * @memberof CustomerEntity
     */
    'timezone': string;
    /**
     * All visible meta (custom) fields registered with this customer
     * @type {Array<CustomerMeta>}
     * @memberof CustomerEntity
     */
    'metaFields'?: Array<CustomerMeta>;
    /**
     * If no team is assigned, everyone can access the customer
     * @type {Array<Team>}
     * @memberof CustomerEntity
     */
    'teams'?: Array<Team>;
    /**
     * 
     * @type {number}
     * @memberof CustomerEntity
     */
    'budget': number;
    /**
     * 
     * @type {number}
     * @memberof CustomerEntity
     */
    'timeBudget': number;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'budgetType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerEntity
     */
    'color'?: string;
}

