/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerRateForm
 */
export interface CustomerRateForm {
    /**
     * User ID
     * @type {number}
     * @memberof CustomerRateForm
     */
    'user'?: number;
    /**
     * The rate (eg. 10.5)
     * @type {number}
     * @memberof CustomerRateForm
     */
    'rate': number;
    /**
     * The internal rate (eg. 10.0 or 10)
     * @type {number}
     * @memberof CustomerRateForm
     */
    'internalRate'?: number;
    /**
     * If \"true\" each time record gets the same rate, regardless of its duration
     * @type {boolean}
     * @memberof CustomerRateForm
     */
    'isFixed'?: boolean;
}

