/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface I18nConfig
 */
export interface I18nConfig {
    /**
     * 
     * @type {string}
     * @memberof I18nConfig
     */
    'formDateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof I18nConfig
     */
    'formDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof I18nConfig
     */
    'dateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof I18nConfig
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof I18nConfig
     */
    'time'?: string;
    /**
     * 
     * @type {string}
     * @memberof I18nConfig
     */
    'duration'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof I18nConfig
     */
    'is24hours'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof I18nConfig
     */
    'now'?: string;
}

