/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Customer } from './customer';

/**
 * 
 * @export
 * @interface ProjectExpanded
 */
export interface ProjectExpanded {
    /**
     * 
     * @type {number}
     * @memberof ProjectExpanded
     */
    'id'?: number;
    /**
     * 
     * @type {Customer}
     * @memberof ProjectExpanded
     */
    'customer': Customer;
    /**
     * 
     * @type {string}
     * @memberof ProjectExpanded
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectExpanded
     */
    'visible': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectExpanded
     */
    'color'?: string;
}

