/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TeamEditFormMembersInner } from './team-edit-form-members-inner';

/**
 * 
 * @export
 * @interface TeamEditForm
 */
export interface TeamEditForm {
    /**
     * Name of the team
     * @type {string}
     * @memberof TeamEditForm
     */
    'name': string;
    /**
     * The hexadecimal color code (default: #d2d6de)
     * @type {string}
     * @memberof TeamEditForm
     */
    'color'?: string;
    /**
     * All team members
     * @type {Array<TeamEditFormMembersInner>}
     * @memberof TeamEditForm
     */
    'members': Array<TeamEditFormMembersInner>;
}

