/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimesheetEditForm
 */
export interface TimesheetEditForm {
    /**
     * 
     * @type {string}
     * @memberof TimesheetEditForm
     */
    'begin': string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetEditForm
     */
    'end'?: string;
    /**
     * Project ID
     * @type {number}
     * @memberof TimesheetEditForm
     */
    'project': number;
    /**
     * Activity ID
     * @type {number}
     * @memberof TimesheetEditForm
     */
    'activity': number;
    /**
     * 
     * @type {string}
     * @memberof TimesheetEditForm
     */
    'description'?: string;
    /**
     * Fixed rate
     * @type {number}
     * @memberof TimesheetEditForm
     */
    'fixedRate'?: number;
    /**
     * Hourly rate
     * @type {number}
     * @memberof TimesheetEditForm
     */
    'hourlyRate'?: number;
    /**
     * User ID
     * @type {number}
     * @memberof TimesheetEditForm
     */
    'user'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimesheetEditForm
     */
    'exported'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TimesheetEditForm
     */
    'billable'?: boolean;
    /**
     * Comma separated list of tags
     * @type {string}
     * @memberof TimesheetEditForm
     */
    'tags'?: string;
}

