/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimesheetConfig
 */
export interface TimesheetConfig {
    /**
     * 
     * @type {string}
     * @memberof TimesheetConfig
     */
    'trackingMode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetConfig
     */
    'defaultBeginTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimesheetConfig
     */
    'activeEntriesHardLimit'?: number;
    /**
     * 
     * @type {number}
     * @memberof TimesheetConfig
     */
    'activeEntriesSoftLimit'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimesheetConfig
     */
    'isAllowFutureTimes'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TimesheetConfig
     */
    'isAllowOverlapping'?: boolean;
}

