/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Team } from './team';
// May contain unused imports in some cases
// @ts-ignore
import { TeamMembership } from './team-membership';

/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'timezone'?: string;
    /**
     * 
     * @type {Array<Team>}
     * @memberof UserEntity
     */
    'teams'?: Array<Team>;
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'avatar'?: string;
    /**
     * 
     * @type {TeamMembership}
     * @memberof UserEntity
     */
    'memberships': TeamMembership;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'accountNumber'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserEntity
     */
    'roles'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'color'?: string;
}

