/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserCollection
 */
export interface UserCollection {
    /**
     * 
     * @type {number}
     * @memberof UserCollection
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    'accountNumber'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserCollection
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    'color'?: string;
}

