/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserEditForm
 */
export interface UserEditForm {
    /**
     * 
     * @type {string}
     * @memberof UserEditForm
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEditForm
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEditForm
     */
    'accountNumber'?: string;
    /**
     * The hexadecimal color code (default: #d2d6de)
     * @type {string}
     * @memberof UserEditForm
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEditForm
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserEditForm
     */
    'language': UserEditFormLanguageEnum;
    /**
     * 
     * @type {string}
     * @memberof UserEditForm
     */
    'timezone': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserEditForm
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserEditForm
     */
    'roles'?: Array<UserEditFormRolesEnum>;
}

export const UserEditFormLanguageEnum = {
    Ar: 'ar',
    Cs: 'cs',
    Da: 'da',
    De: 'de',
    DeAt: 'de_AT',
    DeCh: 'de_CH',
    El: 'el',
    En: 'en',
    Eo: 'eo',
    Es: 'es',
    Eu: 'eu',
    Fi: 'fi',
    Fo: 'fo',
    Fr: 'fr',
    He: 'he',
    Hr: 'hr',
    Hu: 'hu',
    It: 'it',
    Ja: 'ja',
    Ko: 'ko',
    Nl: 'nl',
    Pl: 'pl',
    Pt: 'pt',
    PtBr: 'pt_BR',
    Ro: 'ro',
    Ru: 'ru',
    Sk: 'sk',
    Sv: 'sv',
    Tr: 'tr',
    Vi: 'vi',
    ZhCn: 'zh_CN'
} as const;

export type UserEditFormLanguageEnum = typeof UserEditFormLanguageEnum[keyof typeof UserEditFormLanguageEnum];
export const UserEditFormRolesEnum = {
    Teamlead: 'ROLE_TEAMLEAD',
    Admin: 'ROLE_ADMIN',
    SuperAdmin: 'ROLE_SUPER_ADMIN'
} as const;

export type UserEditFormRolesEnum = typeof UserEditFormRolesEnum[keyof typeof UserEditFormRolesEnum];


