/* tslint:disable */
/* eslint-disable */
/**
 * Kimai - API Docs
 * JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json) 
 *
 * The version of the OpenAPI document: 0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Version
 */
export interface Version {
    /**
     * 
     * @type {string}
     * @memberof Version
     */
    'version'?: string;
    /**
     * Follows the same logic as PHP_VERSION_ID, see https://www.php.net/manual/de/function.phpversion.php
     * @type {number}
     * @memberof Version
     */
    'versionId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Version
     */
    'candidate'?: string;
    /**
     * 
     * @type {string}
     * @memberof Version
     */
    'semver'?: string;
    /**
     * 
     * @type {string}
     * @memberof Version
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Version
     */
    'copyright'?: string;
}

